language: ruby
cache: bundler
rvm:
- 2.1.9
- 2.2.6
- 2.3.3
before_install:
- gem install bundler
deploy:
  gem: smartling
  provider: rubygems
  api_key:
    secure: Sq+xnqlHm/VoOweKbTw7VJyHYfbn32Ri2j0uYufLeF6Fv5iQ0pmz1tluixCCUUq5oXpAw1wERFfP0Mp1bbMrMU0tsKEvfPGecopkeBcXiSKbe/IJnGTONlfvg/sGDzdDoYFmc0lNdVCrcx2mpdWIRdCZ8/MAoQM5r3KAo8DHCI4=
  gemspec: smartling.gemspec
  on:
    tags: true
    rvm: 2.1.9
