language: ruby
rvm:
- 2.2
deploy:
  provider: rubygems
  api_key:
    secure: Sq+xnqlHm/VoOweKbTw7VJyHYfbn32Ri2j0uYufLeF6Fv5iQ0pmz1tluixCCUUq5oXpAw1wERFfP0Mp1bbMrMU0tsKEvfPGecopkeBcXiSKbe/IJnGTONlfvg/sGDzdDoYFmc0lNdVCrcx2mpdWIRdCZ8/MAoQM5r3KAo8DHCI4=
  gemspec: smartling.gemspec
  on:
    tags: true
    rvm: 1.9
